spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

#지정한 Batch Job 만 실행되도록 하기 위해 설정함.args 으로 값이 들어오면 job.name 에 할당, 없을 경우 NONE 으로 배치를 실행하지 않는다는 의미.
spring.batch.job.names: ${job.name:NONE}

---
spring:
  profiles: stage
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver